### ISSUE TITLE
Use different number of hidden unit for each layer

### ISSUE THREAD

**Issue by DimitriF** [farizrahman4u/seq2seq#106]
Hi,
Would it be possible to choose different number of hidden units for each layer and especially for the encoded vector between the encoder and the decoder (not sure "encoded vector" is the right term). 

Something like this:

 `model = Seq2Seq(input_dim=3, input_length=126,
 hidden_dim=(8,16,32, 64, 32,16,8),
 output_length=126, output_dim=3, depth=3)`

Where 8, 16, 32 are the number of hidden units for the encoder part.
64 is the number of hidden unit in the encoded vector.
And finally, 32,16,8 are the number of hidden units in the decoder.

edit:
If I follow your code, what I call "encoded vector" is called "context vector" in seq2seq

**Comment by farizrahman4u** [comment]
You can write custom seq2seq model, following examples in models.py
