### ISSUE TITLE
AttentionSeq2Seq currently broken

### ISSUE THREAD

**Issue by phdowling** [farizrahman4u/seq2seq#110]
After doing a fresh install of recurrentshop and seq2seq:

```python
>>> import seq2seq
Using Theano backend.
>>> from seq2seq.models import AttentionSeq2Seq
>>> 
>>> model = AttentionSeq2Seq(input_dim=5, input_length=7, hidden_dim=10, output_length=8, output_dim=20, depth=4)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dowling/anaconda/lib/python2.7/site-packages/seq2seq/models.py", line 249, in AttentionSeq2Seq
    decoded = decoder(decoded)
  File "/Users/dowling/anaconda/lib/python2.7/site-packages/keras/engine/topology.py", line 470, in __call__
    self.assert_input_compatibility(x)
  File "/Users/dowling/anaconda/lib/python2.7/site-packages/keras/engine/topology.py", line 434, in assert_input_compatibility
    str(x_shape))
Exception: Input 0 is incompatible with layer recurrentcontainer_3: expected shape=(None, 7, 10), found shape=(None, 8, 10)
```

**Comment by phdowling** [comment]
Note: this exception only seems to occur when using deeper models. The tests pass because they use AttentionSeq2Seq with `depth=2`, if you set it to 3 or more, the exception gets thrown.

**Comment by phdowling** [comment]
@farizrahman4u: I wonder about a more general issue with the use of `AttentionDecoderCell`. Shouldn't the `AttentionSeq2Seq` model:

1.  build a decoder that returns a sequence (mostly like the other models except `return_sequences=True`)
2.  create a decoder as a `RecurrentContainer`
3. Add a single `AttentionDecoderCell` to get weighted sums of the input sequence in an LSTM
4. Stack more `LSTMDecoderCell` cells on top if the user wants a deep model

What it actually does in step 4 is to stack **more `AttentionDecoderCell` layers**, which seems a bit strange to me, since attention only plays a role at the "bottom" of the decoder model. 

On top of this, the model actually stacks the AttentionDecoders as layers, not as cells. It would seem to me that this would cause the model to attend over the intermediate decoder outputs repeatedly, which seems strange. Is there any particular reason why the model should be built using `AttentionDecoderCell(...).get_layer(...)` rather than using a single RecurrentContainer?

**Comment by farizrahman4u** [comment]
All done.
