### ISSUE TITLE
Support for teacher forcing?

### ISSUE THREAD

**Issue by phdowling** [farizrahman4u/seq2seq#111]
In decoders, we usually feed the previous timestep's output vector on to the next input vector, language model style. However, in teacher forcing, the ground-truth predictions of the previous timestep are always used, rather than the actual prediction. I suppose a model could still train even without teacher forcing, but often it helps training quite a bit from what I read.

I do not see a way of doing this without providing the teacher inputs as an explicit input to the keras model, though I might be wrong. Now, since in this library we do not supply such inputs I'm guessing this library does not implement teacher forcing, is this correct? If so, are there any plans to perhaps support it in the future?

**Comment by farizrahman4u** [comment]
This will be implemented very shortly.

**Comment by farizrahman4u** [comment]
Teacher forcing is now supported. 
```python
model = Seq2Seq(......., teacher_force=True)
model = AttentionSeq2Seq(....., teacher_force=True)
```

Note that when teacher forcing is enabled, training is done like this:
```python
model.fit([x, y], y)
```
And prediction:
```python
model.predict([x, y])  # Where y is simply np.zeros(output_shape)
```
If you are not satisfied with the API for prediction, you can simply create a new model with `teacher_force=False` and load weights from the model trained with `teacher_force=True`

**Comment by dr-costas** [comment]
I guess by using `fit_on_batch`, we can implement the scheduled sampling, right?

**Comment by phdowling** [comment]
@farizrahman4u : Thanks for implementing this. I noticed you initially added code for teacher forcing in the Attention model as well, any reason this was removed again?

**Comment by farizrahman4u** [comment]
The math isn't right. Also attention seq2seq has no readout. It is also not mentioned in the paper. But I will try to include this somehow.

**Comment by dr-costas** [comment]
Scheduled sampling can go to the models that have readout.

**Comment by bobchennan** [comment]
I agree. Scheduled sampling is just between teacher forcing and basic approach and it should be helpful. Teacher forcing speed up the training process using ground truth and after several epochs when the network converges, we can use prediction result instead of the ground truth to bridge the gap between training and inference. More details can be found in [scheduled sampling](http://papers.nips.cc/paper/5956-scheduled-sampling-for-sequence-prediction-with-recurrent-neural-networks.pdf)

**Comment by riverhxz** [comment]
fail to run  test with teacher force on test 
```python
input_length = 10
input_dim = 2

output_length = 8
output_dim = 3

samples = 100
def test_Seq2Seq():
	x = np.random.random((samples, input_length, input_dim))
	y = np.random.random((samples, output_length, output_dim))

	models = []
	models += [Seq2Seq(output_dim=output_dim, output_length=output_length, input_shape=(input_length, input_dim),teacher_force=True)]
	for model in models:
		model.compile(loss='mse', optimizer='sgd')
		model.fit([x, y], y, nb_epoch=1)
```
and i got this
```
Traceback (most recent call last):
  File "/Users/hehehe/PycharmProjects/seq2seq/tests/test.py", line 58, in <module>
    test_Seq2Seq()
  File "/Users/hehehe/tensorflow/lib/python2.7/site-packages/keras/utils/test_utils.py", line 117, in wrapper
    output = func(*args, **kwargs)
  File "/Users/hehehe/PycharmProjects/seq2seq/tests/test.py", line 33, in test_Seq2Seq
    models += [Seq2Seq(output_dim=output_dim, output_length=output_length, input_shape=(input_length, input_dim),teacher_force=True)]
  File "/Users/hehehe/PycharmProjects/seq2seq/seq2seq/models.py", line 195, in Seq2Seq
    decoded_seq = decoder({'input': encoded_seq, 'ground_truth': inputs[1] if teacher_force else None, 'initial_readout': encoded_seq, 'states': states})
  File "build/bdist.macosx-10.12-intel/egg/recurrentshop/engine.py", line 569, in __call__
  File "/Users/hehehe/tensorflow/lib/python2.7/site-packages/keras/engine/topology.py", line 572, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/Users/hehehe/tensorflow/lib/python2.7/site-packages/keras/engine/topology.py", line 154, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors, mask=input_masks))
  File "build/bdist.macosx-10.12-intel/egg/recurrentshop/engine.py", line 316, in call
  File "build/bdist.macosx-10.12-intel/egg/recurrentshop/engine.py", line 388, in get_initial_states
  File "/Users/hehehe/tensorflow/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 242, in zeros
    return variable(tf.constant_initializer(0., dtype=tf_dtype)(shape), dtype, name)
  File "/Users/hehehe/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/init_ops.py", line 72, in constant_initializer
    def _initializer(shape, dtype=_assert_float_dtype(dtype)):
  File "/Users/hehehe/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/init_ops.py", line 45, in _assert_float_dtype
    raise ValueError("Expected floating point type, got %s." % dtype)
ValueError: Expected floating point type, got <dtype: 'int32'>.
```
am i missing something?

**Comment by farizrahman4u** [comment]
Haven't tested teacher forcing on tensorflow. Can you try it with unroll=True?

**Comment by riverhxz** [comment]
with unroll.
it seems > https://github.com/farizrahman4u/seq2seq/blob/master/seq2seq/models.py#L182
dence does not get the right shape from encode_seq

**Comment by riverhxz** [comment]
>https://github.com/farizrahman4u/seq2seq/blob/master/seq2seq/models.py#L188
it seems dense2 does not get the right shape from encoded_seq.

**Comment by farizrahman4u** [comment]
Did you try it with unroll=True?

**Comment by riverhxz** [comment]
yes. i try with unroll=True
```python
Seq2Seq(output_dim=output_dim, output_length=output_length, input_shape=(input_length, input_dim),unroll=True,teacher_force=True)
```
and exception is 
```log
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1580, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 964, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Users/hehehe/PycharmProjects/seq2seq/tests/test.py", line 58, in <module>
    test_Seq2Seq()
  File "/Users/hehehe/tensorflow/lib/python2.7/site-packages/keras/utils/test_utils.py", line 117, in wrapper
    output = func(*args, **kwargs)
  File "/Users/hehehe/PycharmProjects/seq2seq/tests/test.py", line 33, in test_Seq2Seq
    models += [Seq2Seq(output_dim=output_dim, output_length=output_length, input_shape=(input_length, input_dim),unroll=True,teacher_force=True)]
  File "/Users/hehehe/PycharmProjects/seq2seq/seq2seq/models.py", line 189, in Seq2Seq
    encoded_seq = dense2(encoded_seq)
  File "/Users/hehehe/tensorflow/lib/python2.7/site-packages/keras/engine/topology.py", line 487, in __call__
    self.build(input_shapes[0])
  File "/Users/hehehe/tensorflow/lib/python2.7/site-packages/keras/layers/core.py", line 689, in build
    assert len(input_shape) == 2
TypeError: object of type 'NoneType' has no len()
Exception TypeError: TypeError("'NoneType' object is not callable",) in <function _remove at 0x10f30c668> ignored
```

**Comment by farizrahman4u** [comment]
Thanks, will fix it soon.

**Comment by farizrahman4u** [comment]
I am unable to reproduce this issue on theano backend. @meain Can you try running this on TF backend.

**Comment by meain** [comment]
Yup, I am hitting that error on TF @farizrahman4u

**Comment by ErmiaAzarkhalili** [comment]
@farizrahman4u It's serious issue on TF backend as it raise an error like mentioned above... I would be thankful if you could resolve it...

**Comment by farizrahman4u** [comment]
Ok, will look into it after new years'.

**Comment by ErmiaAzarkhalili** [comment]
Thanks, 
I sent you another issue regarding the package... They seems necessary to get the best  performance of your great package...

⁣Best Regard,
Behrooz​

**Comment by sidsrinivasan** [comment]
Hi, I'm building an autoencoder in Keras, and I have 2 questions:
1) I want to confirm that teacher forcing is only 'active' during training time, and is turned off when you use keras' predict() function? In my current implementation, my code does something like:
`decoder = RecurrentContainer(...)
_decoded = decoder({input: ..., 'ground_truth':...})`
as I found in the seq2seq code...

2) I'm adding a TimeDistributedDense layer with softmax activation after the RecurrentContainer, and when I print model.summary(), RecurrentContainer's output is the correct dimension (nb_samples, timesteps, output_dim), while the softmax layer's output is ((nb_samples, intermediate_dim), timesteps, output_dim). This is only the case when I set my ground_truth input in RecurrentContainer and goes away otherwise, and I'm not sure why teacher forcing is changing the output dimension of the subsequent layer.

Thanks!

**Comment by smodlich** [comment]
@farizrahman4u @phdowling Was somebody able to get teacher_force to work with model.predict? The simple way model.predict([x,y]) does not work for me. I created a separate issue: [Prediction with teacher force](https://github.com/farizrahman4u/seq2seq/issues/160)

**Comment by ShivaliGoel** [comment]
when specifying ([x,y],y) in model.fit I get the following error 

ValueError: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 1 arrays but instead got the following list of 2 arrays 

Please help !!
