### ISSUE TITLE
theano.gof.fg.MissingInputError:

### ISSUE THREAD

**Issue by sharathadavanne** [farizrahman4u/seq2seq#112]
Hi, 

When I use the AttentionSeq2Seq and I add a TimeDitributed(Dense) at the end I get the error: 

> theano.gof.fg.MissingInputError: ("An input of the graph, used to compute dot(<TensorType(float32, matrix)>, HostFromGpu.0), was not provided and not given a value.Use the Theano flag exception_verbosity='high',for more information on this error.", <TensorType(float32, matrix)>)

I have tried three approaches. 

1)
 ```python
import keras
import seq2seq
from seq2seq.models import AttentionSeq2Seq

model_seq2seq = AttentionSeq2Seq(input_dim=5, input_length=7, hidden_dim=10, output_length=8, output_dim=20, depth=4)

model = keras.models.Sequential()
model.add(model_seq2seq)
model.add(keras.layers.TimeDisgtributed(keras.layers.Dense(1)))
model.compile(loss='binary_crossentropy', optimizer='adam')
```

2) 
 ```python
import keras
import seq2seq
from seq2seq.models import AttentionSeq2Seq

model_seq2seq = AttentionSeq2Seq(input_dim=5, input_length=7, hidden_dim=10, output_length=8, output_dim=20, depth=4)

model = keras.models.Sequential()
model.add(keras.layers.Lamda(lamda x: x, input_shape=(7, 5)))
model.add(model_seq2seq)
model.add(keras.layers.TimeDisgtributed(keras.layers.Dense(1)))
model.compile(loss='binary_crossentropy', optimizer='adam')
 ```

3)(in a custom class to handle the model) 
 ```python 
import seq2seq
import keras
from seq2seq.models import AttentionSeq2Seq, LSTMDecoderCell, AttentionDecoderCell
from recurrentshop import LSTMCell, RecurrentContainer
from keras.layers import Dense, Dropout, TimeDistributed, Bidirectional, Input

depth = [self._depth_encoder, self._depth_decoder]
        shape = (None, self._input_length, self._nb_features)
        hidden_dim = self._hidden_output_dim
        encoder = RecurrentContainer(
            stateful=False,
            return_sequences=True,
            input_length=shape[1]
        )

        encoder.add(LSTMCell(hidden_dim, batch_input_shape=(shape[0], shape[2])))

        for _ in range(1, depth[0]):
            encoder.add(keras.layers.Dropout(self._dropout))
            encoder.add(LSTMCell(hidden_dim))

        input_layer = Input(batch_shape=shape)
        encoder = Bidirectional(encoder, merge_mode=self._merge_mode)
        encoded = encoder(input_layer)

        decoded = encoded

        for _ in range(1, depth[1]):
            decoded = Dropout(self._dropout)(decoded)

            decoder = AttentionDecoderCell(
                output_dim=hidden_dim,
                hidden_dim=hidden_dim,
                batch_input_shape=(shape[0], shape[1], hidden_dim)
            ).get_layer(
                    decode=True,
                    output_length=self._output_length,
                    unroll=False,
                    stateful=False
            )

            decoded = decoder(decoded)

        decoded = Dropout(self._dropout)(decoded)

        decoder = AttentionDecoderCell(
            output_dim=self._hidden_output_dim,
            hidden_dim=hidden_dim,
            batch_input_shape=(
                shape[0],
                self._output_length if depth[1] > 1 else shape[1], hidden_dim
            )
        ).get_layer(
            decode=True,
            output_length=self._output_length,
            unroll=False,
            stateful=False
        )

        decoded = decoder(decoded)

        decoded = Dropout(self._dropout)(decoded)

        decoded = TimeDistributed(
            Dense(
                self._output_dim,
                activation=self._output_activation
            ),
            name='TD'
        )(decoded)

        self._model = keras.models.Model(input_layer, decoded)
        self._model.compile(
            loss=self._loss,
            optimizer=self._optimizer
        )
 ```

None of the above works. So, how can I add a Dense at the end of the AttentionSeq2Seq model?

P.S. The last one gives the followuing summary: 
>
input_1 (InputLayer)             (None, 1291, 64)      0                                            
____________________________________________________________________________________________________
bidirectional_1 (Bidirectional)  (None, 1291, 64)      198144      input_1[0][0]                    
____________________________________________________________________________________________________
dropout_3 (Dropout)              (None, 1291, 64)      0           bidirectional_1[0][0]            
____________________________________________________________________________________________________
recurrentcontainer_2 (RecurrentCo(None, 10, 64)        37313       dropout_3[0][0]                  
____________________________________________________________________________________________________
dropout_4 (Dropout)              (None, 10, 64)        0           recurrentcontainer_2[0][0]       
____________________________________________________________________________________________________
recurrentcontainer_3 (RecurrentCo(None, 10, 64)        37313       dropout_4[0][0]                  
____________________________________________________________________________________________________
dropout_5 (Dropout)              (None, 10, 64)        0           recurrentcontainer_3[0][0]       
____________________________________________________________________________________________________
TD (TimeDistributed)             (None, 10, 5421)      352365      dropout_5[0][0]

**Comment by dr-costas** [comment]
Hi, 

I'm working together to a task with the user @sharathadavanne and we are using the same code. 

The issue seems to go away if we remove the line: 

`encoder.add(keras.layers.Dropout(self._dropout))`

In general, even at the provided examples and the original code, the addition of Dropout in the encoder seems to cause the MssingInputError.

**Comment by farizrahman4u** [comment]
Update recurrentshop and seq2seq.

If model.fit works and model.predict doesn't : 

* Train a model with dropout
* Create a new model with same config but without dropout (dropout=0)
* Copy weights from trained model to new model
* Predict using new model
