### ISSUE TITLE
Sequence padding and bucketing

### ISSUE THREAD

**Issue by ishalyminov** [farizrahman4u/seq2seq#120]
If I have input/output sequences of different length and I want to pad/bucket them as proposed [here](https://www.tensorflow.org/versions/r0.11/tutorials/seq2seq/index.html), how do I do that?

Seq2Seq models here require `output_length`, and if I pass `None` as one, I get the error:

> `AssertionError: Missing argument: output_length should be specified for decoders.`

**Comment by phdowling** [comment]
Your `output_length` is the *maximum* length of sequences you want to generate. They can of course be shorter. I usually train these models to predict a special `<STOP>` symbol when they generate output. 

So what you want to do (I think) is add a stop symbol to your output sequences, pre-pad your input sequences with 0 values (or vectors), and post-pad your outputs, so they each always have the same length (respectively).  You can use `keras.preprocessing.sequence.pad_sequences` for this.

Speaking of this though, I'm not sure if post-padded 0 values in output sequences are automatically masked by the error functions in Keras. If someone has some insight, would be interesting to know about this.

**Comment by ishalyminov** [comment]
Thank you!
> So what you want to do (I think) is add a stop symbol to your output sequences, pre-pad your input sequences with 0 values (or vectors), and post-pad your outputs, so they each always have the same length (respectively)

And if I have several buckets of padded sequences (as tensorflow developers suggest in the link I gave), will the same model works with them? Or one needs to train a separate model for each (max_input_len, max_output_len) bucket? (That is not desirable as it reduces the amount of training data for each of them).

**Comment by ishalyminov** [comment]
Well, regarding my last question, I suppose the right way is to have separate models for each (input, output) bucket but share weights of hidden layers across all of them - in theory, that would work nicely and make the proper use of the entire dataset.

**Comment by ishalyminov** [comment]
Assuming that different bucketed models with shared layers is the right approach, is there a preference in order in which one trains such bucketed systems - sequence length ascending or descending?

**Comment by seeiespi** [comment]
@ishalyminov, were you able to use the get_weights and set_weight functions in the Model API to run the same model on the different set of buckets?

**Comment by ishalyminov** [comment]
@seeiespi sorry, it's been a while since I stopped working on this..
