### ISSUE TITLE
PAD, GO, STOP symbols with embeddings

### ISSUE THREAD

**Issue by ishalyminov** [farizrahman4u/seq2seq#128]
I want to use embeddings as both encoder inputs and decoder outputs. How do I deal with special symbols?
Do I just add them to my embedding mapping as some dummy vectors?

**Comment by phdowling** [comment]
That's how I usually do it. Padding is usually 0 (useful for masking), any other special symbols you can just encode as ids 1, 2, .. in your vocab and then add your regular words after that

**Comment by ishalyminov** [comment]
Thanks! I'll also need to make up 'fake embeddings' for them - like [0.0, 0.0, ..., 0.0], [1.0, 1.0, ..., 1.0] and so on (as I'll need to somehow identify PAD and STOP at the decoder's output)- and I'm concerned about choosing the right vectors so that they don't break anything in the embedding space. Are there any known limitations for such?

**Comment by phdowling** [comment]
Just treat them as normal tokens, the network should take care of learning "sensible" weights for them
