### ISSUE TITLE
example/train.py

### ISSUE THREAD

**Issue by hungryquiter** [farizrahman4u/seq2seq#135]
i think 
model.fit([batch[0],batch[1]], batch[1], nb_epoch=1)
should be 
model.fit(batch[0], batch[1], nb_epoch=1)

what is the mean of [batch[0],batch[1]],  is it two input, but the model have only one input

**Comment by farizrahman4u** [comment]
Oops, i didn't mean to push the example yet. 
Btw, model.fit([x,y], y) is the format for teacher forcing.

**Comment by hungryquiter** [comment]
what is your mean, is the example couldn't run.
you don't finish the example yet
