### ISSUE TITLE
Seq2Seq example gives error

### ISSUE THREAD

**Issue by dr-costas** [farizrahman4u/seq2seq#141]
Hi, 

I tried the exact example from the landing page of seq2seq:

```python

model = Seq2Seq(batch_input_shape=(16, 7, 5), hidden_dim=10, output_length=8, output_dim=20, depth=4)
model.compile(loss='mse', optimizer='rmsprop')
```

and I get:

>File "seq2seq/models.py", line 190, in Seq2Seq
    {'input': encoded_seq, 'ground_truth': inputs[1] if broadcast_state else None, 'initial_readout': encoded_seq,
IndexError: list index out of range

**Comment by farizrahman4u** [comment]
Works for me. Python 2. 7 / Theano
What is your config?
