### ISSUE TITLE
seq2seq/tests/test.py seem to fail with tensor flow 0.11.0 

### ISSUE THREAD

**Issue by ksrinivs64** [farizrahman4u/seq2seq#151]
Running the tests with py.test causes test_Seq2Seq and test_AttentionSeq2Seq to fail.  

For test_Seq2Seq:
/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py:353: in make_tensor_proto
    _AssertCompatible(values, dtype)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

values = 0.0, dtype = tf.int32

    def _AssertCompatible(values, dtype):
      fn = _TF_TO_IS_OK.get(dtype, _FilterNotTensor)
      mismatch = fn(values)
      if mismatch is not None:
        if dtype is None:
          raise TypeError("List of Tensors when single Tensor expected")
        else:
          raise TypeError("Expected %s, got %s of type '%s' instead." %
>                         (dtype.name, repr(mismatch), type(mismatch).__name__))
E         TypeError: Expected int32, got 0.0 of type 'float' instead.

For test_AttentionSeq2Seq:
/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/ops.py:1783: in set_shapes_for_outputs
    shapes = shape_func(op)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

op = <tensorflow.python.framework.ops.Operation object at 0x121d74160>
input_tensors_needed = None, debug_python_shape_fn = None

    def call_cpp_shape_fn(op, input_tensors_needed=None,
                          debug_python_shape_fn=None):
      """A shape function that delegates to the registered C++ shape function.
    
      Args:
        op: the node in the graph for which to compute output shapes.
        input_tensors_needed: a list of input tensor indices for which to compute
          the input tensor's value and pass to the C++ shape function.
        debug_python_shape_fn: For testing only during migration to using
          call_cpp_shape_fn. Do not submit calls that set this,
          as the comparison is slow. If non-None, the python shape function;
          this function will be called and its output compared to that of
          the C++ shape function.
    
      Returns:
        A TensorShape list of the output shapes of the op, as computed using the
        C++ shape inference function registered for the op.
    
      Raises:
        ValueError: If the C++ shape function returned an error (e.g. because the
        shapes of the inputs are of the wrong rank or otherwise incompatible
        according to the shape function).
      """
      node_def_str = op.node_def.SerializeToString()
      input_shapes = [i.get_shape().as_proto().SerializeToString() for i in
                      op.inputs]
    
      input_tensors = [None for i in input_shapes]
      if input_tensors_needed:
        for idx in input_tensors_needed:
          input_tensors[idx] = tensor_util.constant_value(op.inputs[idx])
          if input_tensors[idx] is not None:
            input_tensors[idx] = np.asarray(input_tensors[idx])
    
      try:
        with errors.raise_exception_on_not_ok_status() as status:
          output_shapes = pywrap_tensorflow.RunCppShapeInference(node_def_str,
                                                                 input_shapes,
                                                                 input_tensors,
                                                                 status)
      except errors.InvalidArgumentError as err:
>       raise ValueError(err.message)
E       ValueError: Shapes must be equal rank, but are 0 and 1

**Comment by Poppy856** [comment]
same problem！ Crying
