### ISSUE TITLE
Prediction with teacher forcing

### ISSUE THREAD

**Issue by smodlich** [farizrahman4u/seq2seq#160]
Hi,
I used Seq2Seq model with teacher_force=True. Trainings works, but I am not able to make predictions with the model, because of an error with keras_learning_phase. The error is:

`theano.gof.fg.MissingInputError: ("An input of the graph, used to compute if{}(keras_learning_phase, DimShuffle{1,0,2}.0, DimShuffle{1,0,2}.0), was not provided and not given a value.Use the Theano flag exception_verbosity='high',for more information on this error.", keras_learning_phase)
`
Code (Error occures in last line):
`
main_Input=Input(shape=(SEQ_LEN,),name="main_input",dtype="int32")
x= Embedding(INPUT_VOC_SIZE,EMBEDDING_SIZE,input_length=SEQ_LEN,mask_zero=True)(main_Input)
forced_input=Input(shape=(TARGET_LEN,),name="sec_input",dtype="int32")
y=Embedding(INPUT_VOC_SIZE+1,EMBEDDING_SIZE,input_length=SEQ_LEN,mask_zero=True)(forced_input)    x=Seq2Seq(output_dim=OUTPUT_DIM,output_length=TARGET_LEN,hidden_dim=HIDDEN,input_length=SEQ_LEN,input_dim=EMBEDDING_SIZE,depth=DEPTH,peek=True,teacher_force=True)([x,y])
x= TimeDistributed(Dense(TARGET_VOC_SIZE,activation="softmax"))(x)
model=Model(input=[main_Input,forced_input],output=[x])
rms = optimizers.RMSprop(lr=0.001)
model.compile(loss='sparse_categorical_crossentropy', optimizer=rms)
prediction = model.predict([pad_input_seq, tf_input])`

I tried using K.function but same error:

`
prediction=K.function([K.learning_phase(),model.layers[0].input,model.layers[1].input],[model.layers[-1].output])`

Was somebody able to get teacher_force to work with either Theano or Tensorflow Backend?

**Comment by smodlich** [comment]
Issue was related to model saving. When I save the model with model.save_weights instead of pickle the line model.predict([pad_input_seq, tf_input]) works.

**Comment by boyaryn** [comment]
I can't get teacher_force=True work.

```
def build_model_3(batch_size, seq_length, input_dim, hidden_size, n_levels):
    from keras.layers import Activation
    from keras.models import Sequential
    from seq2seq.models import Seq2Seq

    model = Sequential()
    model.add(Seq2Seq(output_dim=n_levels+1, output_length=seq_length,
                      batch_input_shape=(batch_size, seq_length, input_dim),
                      hidden_dim=hidden_size, stateful=True, teacher_force=True, peek=True, dropout=0.2))
    model.add(Activation('softmax'))
    model.compile(optimizer='rmsprop', loss='categorical_crossentropy',
                  metrics=['accuracy'], sample_weight_mode='temporal')
    return model

batch_size = 64
seq_length = 32
input_dim = 85
lstm_output_size = 256
n_levels = 9
train_model = build_model_3(batch_size, seq_length, input_dim, lstm_output_size, n_levels)
...
loss = 0
...
# batch_input has shape (64, 32, 85), batch_labels - (64, 32, 10), batch_sample_weight - (64, 32)
loss += model.train_on_batch([batch_input, batch_labels], batch_labels, sample_weight=batch_sample_weight)[0]
```
I get exception

>  /usr/local/lib/python3.5/dist-packages/Keras-2.0.4-py3.5.egg/keras/models.py in train_on_batch(self, x, y, class_weight, sample_weight)
    954         return self.model.train_on_batch(x, y,
    955                                          sample_weight=sample_weight,
--> 956                                          class_weight=class_weight)
    957 
    958     def test_on_batch(self, x, y,
/usr/local/lib/python3.5/dist-packages/Keras-2.0.4-py3.5.egg/keras/engine/training.py in train_on_batch(self, x, y, sample_weight, class_weight)
   1636             ins = x + y + sample_weights
   1637         self._make_train_function()
-> 1638         outputs = self.train_function(ins)
   1639         if len(outputs) == 1:
   1640             return outputs[0]
/usr/local/lib/python3.5/dist-packages/Keras-2.0.4-py3.5.egg/keras/backend/tensorflow_backend.py in __call__(self, inputs)             [36/1995]
   2264                 value = (indices, sparse_coo.data, sparse_coo.shape)
   2265             feed_dict[tensor] = value
-> 2266         session = get_session()
   2267         updated = session.run(self.outputs + [self.updates_op],
   2268                               feed_dict=feed_dict)
/usr/local/lib/python3.5/dist-packages/Keras-2.0.4-py3.5.egg/keras/backend/tensorflow_backend.py in get_session()
    163     if not _MANUAL_VAR_INIT:
    164         with session.graph.as_default():
--> 165             _initialize_variables()
    166     return session
    167 
/usr/local/lib/python3.5/dist-packages/Keras-2.0.4-py3.5.egg/keras/backend/tensorflow_backend.py in _initialize_variables()
    336     if uninitialized_variables:
    337         sess = get_session()
--> 338         sess.run(tf.variables_initializer(uninitialized_variables))
    339
    340                                                                                                                                [17/1995]
/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    787     try:
    788       result = self._run(None, fetches, feed_dict, options_ptr,
--> 789                          run_metadata_ptr)
    790       if run_metadata:
    791         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)
/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
    995     if final_fetches or final_targets:
    996       results = self._do_run(handle, final_targets, final_fetches,
--> 997                              feed_dict_string, options, run_metadata)
    998     else:
    999       results = []
/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options,
 run_metadata)
   1130     if handle is None:
   1131       return self._do_call(_run_fn, self._session, feed_dict, fetch_list,
-> 1132                            target_list, options, run_metadata)
   1133     else:
   1134       return self._do_call(_prun_fn, self._session, handle, feed_dict,
/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1150         except KeyError:
   1151           pass
-> 1152       raise type(e)(node_def, op, message)
   1153 
   1154   def _extend_graph(self):
InvalidArgumentError: The node 'recurrent_sequential_2/while_1/Variable_1/Assign' has inputs from different frames. The input 'recurrent_sequent
ial_2/while_1/Const_1' is in frame 'recurrent_sequential_2/while_1/recurrent_sequential_2/while_1/'. The input 'recurrent_sequential_2/while_1/V
ariable_1' is in frame ''.

What am I doing wrong?

**Comment by ShivaliGoel** [comment]
when specifying ([x,y],y) in model.fit I get the following error 

ValueError: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 1 arrays but instead got the following list of 2 arrays
