### ISSUE TITLE
Pip install not working

### ISSUE THREAD

**Issue by Spider101** [farizrahman4u/seq2seq#165]
The installation instructions in the Readme (install with pip) did not work for me.

```sudo pip install git+ssh://github.com/farizrahman4u/seq2seq.git```

Running the above line gave me the following error: 
``` Could not find a version that satisfies the requirement recurrentshop (from seq2seq==0.1.0) (from versions: ) No matching distribution found for recurrentshop (from seq2seq==0.1.0)```

Do I have to install recurrentshop separately?

**Comment by smodlich** [comment]
If you install recurrentshop (first) separately, it works.

**Comment by sunnysai12345** [comment]
Do  pip install git+https://github.com/datalogai/recurrentshop.git Use sudo if you are using linux distribution.

**Comment by Spider101** [comment]
Thank you. I will do so. I just feel it would have been more efficient if the dependencies were also installed through the pip installation of the seq2seq library.

**Comment by sxpistols** [comment]
on mac & python3.6

pip3 install git+https://github.com/datalogai/recurrentshop.git
pip3 install git+https://github.com/farizrahman4u/seq2seq.git

**Comment by absognety** [comment]
> on mac & python3.6
> 
> pip3 install git+https://github.com/datalogai/recurrentshop.git
> pip3 install git+https://github.com/farizrahman4u/seq2seq.git

There is a issue in `recurrentshop/engine.py`:

```
>>> import recurrentshop
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vikas/anaconda3/lib/python3.7/site-packages/recurrentshop/__init__.py", line 1, in <module>
    from .engine import *
  File "/home/vikas/anaconda3/lib/python3.7/site-packages/recurrentshop/engine.py", line 10, in <module>
    if K.backend() == 'tensorflow':
NameError: name 'K' is not defined
```
Fix:
```
Add this line `from keras import backend as K` to `engine.py` to fix this then proceed to install `seq2seq` as mentioned above

**Comment by kunkun1230** [comment]
> > on mac & python3.6
> > pip3 install git+https://github.com/datalogai/recurrentshop.git
> > pip3 install git+https://github.com/farizrahman4u/seq2seq.git
> 
> There is a issue in `recurrentshop/engine.py`:
> 
> ```
> >>> import recurrentshop
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/vikas/anaconda3/lib/python3.7/site-packages/recurrentshop/__init__.py", line 1, in <module>
>     from .engine import *
>   File "/home/vikas/anaconda3/lib/python3.7/site-packages/recurrentshop/engine.py", line 10, in <module>
>     if K.backend() == 'tensorflow':
> NameError: name 'K' is not defined
> ```
> 
> Fix:
> Add this line `from keras import backend as K` to `engine.py` to fix this then proceed to install `seq2seq` as mentioned above.

Cool，this works well
