### ISSUE TITLE
Error in Importing seq2seq

### ISSUE THREAD

**Issue by amirveyseh** [farizrahman4u/seq2seq#169]
Hi

I've followed your instruction for installing seq2seq and it said seq2seq 0.1.0 was successfully installed. But when I try your to import seq2seq in python I get this error:

Traceback (most recent call last):
  File "./seq2seqRNN.py", line 1, in <module>
    import seq2seq
  File "build/bdist.linux-x86_64/egg/seq2seq/__init__.py", line 1, in <module>
    #!/usr/bin/python
  File "build/bdist.linux-x86_64/egg/seq2seq/cells.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/recurrentshop/__init__.py", line 1, in <module>
    #!/usr/bin/python
  File "build/bdist.linux-x86_64/egg/recurrentshop/engine.py", line 3, in <module>
ImportError: cannot import name initializations

**Comment by pradeepbn** [comment]
This requires older version of keras:

pip install https://github.com/fchollet/keras/tarball/1.1.0

**Comment by DominguesM** [comment]
https://github.com/sunnysai12345/recurrentshop

Best solution at the moment

**Comment by fritshermans** [comment]
if i use the version above (from sunnysai12345) i get the following error:
`TypeError: __call__() got an unexpected keyword argument 'name'`
i'm using python 3.5 with the latest version of keras and tensor flow

**Comment by 0xnurl** [comment]
@fritshermans Line #80 in `engine.py` should be changed to `self.value = init(value)` (remove `name=name`)
In any case this fix leads to more errors due to Keras 2 incompatibility.

**Comment by Blockost** [comment]
Doesn't seq2seq support Keras 2.0 yet ?

**Comment by farizrahman4u** [comment]
Yes.
