### ISSUE TITLE
ImportError: cannot import name weight

### ISSUE THREAD

**Issue by Huarong** [farizrahman4u/seq2seq#171]
```
  File "/Users/huohuarong/Library/Python/2.7/lib/python/site-packages/seq2seq/__init__.py", line 1, in <module>
    from .cells import *
  File "/Users/huohuarong/Library/Python/2.7/lib/python/site-packages/seq2seq/cells.py", line 1, in <module>
    from recurrentshop import RNNCell, LSTMCell, weight
ImportError: cannot import name weight
```

There is no `weight` in recurrentshop

**Comment by xrw** [comment]
The same problem. Maybe we should use an older version of recurrentshop..?

**Comment by PraveenKumarCSE** [comment]
Hi folks...
Finally I found the solution for "ImportError: cannot import name weight". Latest recurrentshop lib has no weight function. So only that error is throwing. finally I found another recurrentshop lib with weight function. Please download lib from following link and recompile the recurrentshop. Then try to run.
Link : https://github.com/sunnysai12345/recurrentshop

**Comment by PratsBhatt** [comment]
I did this. It is still not working.

**Comment by dmitriydligach** [comment]
Same problem here :(
