### ISSUE TITLE
'Keyword argument not understood:', 'input_length'

### ISSUE THREAD

**Issue by MeteorKepler** [farizrahman4u/seq2seq#176]
When i use Seq2Seq model, this error will always occur:
```
File "/Users/meteorhub/anaconda/lib/python3.6/site-packages/keras/layers/recurrent.py", line 186, in __init__
    super(Recurrent, self).__init__(**kwargs)
  File "/Users/meteorhub/anaconda/lib/python3.6/site-packages/keras/engine/topology.py", line 281, in __init__
    raise TypeError('Keyword argument not understood:', kwarg)
TypeError: ('Keyword argument not understood:', 'input_length')
```

Is there any solutions?

**Comment by lhl881210** [comment]
Same problem.

**Comment by Zeco-01** [comment]
I have the same problem when using the code from 'seq2seq-1' branch. I found that 'input_length' is not in the variable 'allowed_kwargs', which is at line 270 in keras/engine/topology.py:
`allowed_kwargs = {
'input_shape',
'batch_input_shape',
'batch_size',
'dtype',
'name',
'trainable',
'weights',
'input_dtype'
}`
I think this is the cause of the problem, but I have no idea how to fix it.
