### ISSUE TITLE
AttributeError: 'LSTMCell' object has no attribute 'batch_input_shape'

### ISSUE THREAD

**Issue by PraveenKumarCSE** [farizrahman4u/seq2seq#182]
Hi
  When I start to run this application, I had got the error in weight function. Now I have updated seq2seq and recurrentshop lib. Now weight function error is fixed. 
  But now I am getting another new error is called AttributeError: 'LSTMCell' object has no attribute 'batch_input_shape'. I have verified the code. But I cannot find batch_input_shape object.

 Please any found the solution kindly let me know.

**Comment by dhrushilbadani** [comment]
Have you tried using batch_shape instead?
