### ISSUE TITLE
Import of seq2seq does not work regardless of how to install `seq2seq`

### ISSUE THREAD

**Issue by kootenpv** [farizrahman4u/seq2seq#184]
It's very unprofessional not to be able to install....

Perhaps it is possible to update the README to contain `pip install git+<working_branch>`, and also which `recurrentshop` commit works.

**Comment by mrelich** [comment]
You can simply clone the repository, cd into the directory and then do `pip install .`

**Comment by mehrdadscomputer** [comment]
@mrelich 
`pip install` will show this error:
```
Could not find a version that satisfies the requirement recurrentshop 
(from seq2seq==0.1.0) (from versions: )
No matching distribution found for recurrentshop (from seq2seq==0.1.0)
```

**Comment by kootenpv** [comment]
@mrelich My apologies, the problem is not the installation, the problem is the importing afterwards. I've tried multiple commit hash versions from both `seq2seq` and `recurrentshop`
