### ISSUE TITLE
ImportError: cannot import name weight in test.py

### ISSUE THREAD

**Issue by VisheshTanwar-IITR** [farizrahman4u/seq2seq#185]
Hey fariz
I am totally new to coding language and  I am using python for my work. I was running your Seq2Seq code but it is showing error regarding the " weights". 

File "test.py", line 1, in <module>
    from seq2seq import SimpleSeq2Seq, Seq2Seq, AttentionSeq2Seq
  File "/usr/local/lib/python2.7/dist-packages/seq2seq/__init__.py", line 1, in <module>
    from .cells import *
  File "/usr/local/lib/python2.7/dist-packages/seq2seq/cells.py", line 1, in <module>
    from recurrentshop import RNNCell, LSTMCell, weight
ImportError: cannot import name weight

How do I fix this error? Also, I am unable to use this code for my own dataset? Can you plz help me out?

Thanks

**Comment by kgoba** [comment]
I get a similar error just by importing seq2seq. I have installed both seq2seq and recurrentshop from the latest versions in the github repository. Python 2.7.

>>> import seq2seq
Using TensorFlow backend.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/seq2seq/__init__.py", line 1, in <module>
    from .cells import *
  File "/usr/local/lib/python2.7/dist-packages/seq2seq/cells.py", line 1, in <module>
    from recurrentshop import RNNCell, LSTMCell, weight
ImportError: cannot import name weight

**Comment by mrelich** [comment]
I ran into the same error.  It seems the backend package recurrentshop is undergoing some changes.  You can go back to an older version of recurrentshop (sometime in 2016) *and* an older version of keras.  Otherwise you have to wait for seq2seq to catch up to the backend.

**Comment by VisheshTanwar-IITR** [comment]
Thanks @kgoba  @mrelich 

@mrelich  Dis your issue resolve? Which version of recurrent-shop and keras you used to fix it?
