### ISSUE TITLE
Invalid layer: SimpleSeq2seq

### ISSUE THREAD

**Issue by lifeng1989** [farizrahman4u/seq2seq#24]
when I try to use model_from_json(open(NN_MODEL_PATH1).read()   to read the model from the model text. i have this trouble .  thanks for your time.

**Comment by farizrahman4u** [comment]
its because of custom layers in seq2seq. I will fix it soon. In the mean time, yo can use `CPickle` to save and load your models.

**Comment by mbollmann** [comment]
Any update on this? I have quite a bit of trouble saving a model that looks like this:

```
[<keras.layers.embeddings.Embedding object at 0x7f48ebf6ffd0>, <seq2seq.models.SimpleSeq2seq object at 0x7f48ebf7b080>, <keras.layers.core.Activation object at 0x7f48ebf40080>]
```

I can pickle the layers separately, but pickling the full (compiled!) model gives me a RuntimeError "maximum recursion depth exceeded".

- - -

Also, shouldn't it be possible to use custom layers with Keras? You can do something like:

```
from keras.models import model_from_json
from seq2seq.models import Seq2seq
model = model_from_json(foo, custom_objects={'Seq2seq': Seq2seq})
```

But this complains about missing positional arguments (output_dim, hidden_dim, output_length). I'm not sure why they don't get supplied properly when it appears to work with native Keras layers...

**Comment by farizrahman4u** [comment]
You can increase your recursion limit using `sys.setrecursionlimit(100000)

**Comment by mbollmann** [comment]
Thanks, that worked. I just assumed there was some endless loop somewhere, it hadn't occured to me that the default recursion limit might actually be too low for these models.

**Comment by htw2012** [comment]
I set the  recursion limit .

`import sys;
sys.setrecursionlimit(1000000) `



Another error I got like below：

`theano.gof.fg.MissingInputError: An input of the graph, used to compute DimShuffle{x,x,x}(keras_learning_phase), was not provided and not given a value.Use the Theano flag exception_verbosity='high',for more information on this error.

Backtrace when the variable is created:
  File "/home/towan/PycharmProjects/test_keras/test_p2w/keras_p2w_onehot_common_rev_batch.py", line 11, in <module>
    from model_build import build_model,build_model_attetion
  File "/home/towan/PycharmProjects/test_keras/test_p2w/model_build.py", line 10, in <module>
    from keras.models import Sequential
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.0.3-py2.7.egg/keras/__init__.py", line 2, in <module>
    from . import backend
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.0.3-py2.7.egg/keras/backend/__init__.py", line 56, in <module>
    from .theano_backend import *
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.0.3-py2.7.egg/keras/backend/theano_backend.py", line 17, in <module>
    _LEARNING_PHASE = T.scalar(dtype='uint8', name='keras_learning_phase')  # 0 = test, 1 = train`
