### ISSUE TITLE
Layer Attribute Error when building seq2seq.py script

### ISSUE THREAD

**Issue by LeavesBreathe** [farizrahman4u/seq2seq#3]
Hey Fariz,

I'm having a basic error that I think should be easy to resolve. When I use seq2seq.py, I keep getting the following error: Note that this occurs when I define the seq2seq model:

    seq2seq = Seq2seq(
        input_length=x_maxlen*x_sent_len, 
        input_dim=word2vec_dimension,
        hidden_dim=hidden_variables_encoding,
        output_dim=y_matrix_axis, 
        output_length=y_sent_len*2,
        batch_size = batch_size/2, 
        depth=4)

`AttributeError: 'Seq2seq' object has no attribute 'layers'`

This occurs on line 61, when you do self.add(l).

Before line 61, if I write in:

```self = Sequential()```

It resolves the error, but then I can't add any more layers after the seq2seq model on my main script. Again I'm faced with the same error:

```AttributeError: 'Seq2seq' object has no attribute 'layers'```

Thanks alot! I feel that I should be able to figure this out, but I"m just not getting it.

**Comment by LeavesBreathe** [comment]
As a work around, I just pasted the class into my main script and this resolved it, so I'm gonna close this.

**Comment by farizrahman4u** [comment]
@LeavesBreathe This has been fixed.
