### ISSUE TITLE
Question: Using AttentionDecoder without an encoder

### ISSUE THREAD

**Issue by jitoledo** [farizrahman4u/seq2seq#35]
Hello, 

Reading the paper "Neural Machine Translation by Jointly learning to transcribe and align" I thought that the only input required by the Decoder was a sequence of annotations. 
Am I supposed to be able to use your AttentionDecoder without an encoder? I mean, I have a set of annotations comming from a CNN similar to the paper "Show, Attend and Tell: Neural Image Caption
Generation with Visual Attention".  There is no "hidden state" from the encoder to initialize de decoder. Also I had to force the input_shape parameter (even if its not the first layer in the model).

I have a layer whose output_shape is (n_timesteps, feature_dimmension) and I would like to add an 
AttentionDecoder layer (output_length=16).
Before my final layer that is a TimeDistributedDense(nb_classes,activation='softmax')

Looking at your attention model example I see you create the attentiondecoder layer like this:
AttentionDecoder(hidden_dim=hidden_dim, output_length=output_length, state_input=False, **kwargs)

In my code I tried to use:
model.add(AttentionDecoder(hidden_dim=128, output_length=16, state_input=False))
that fails with an error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./seq2seq/seq2seq/layers/decoders.py", line 44, in __init__
    super(LSTMDecoder, self).__init__(**kwargs)
  File "./seq2seq/seq2seq/layers/state_transfer_lstm.py", line 13, in __init__
    super(StateTransferLSTM, self).__init__(**kwargs)
TypeError: __init__() takes at least 2 arguments (1 given)

Then I tried to specify the input_shape
model.add(AttentionDecoder(hidden_dim=128, output_length=16, state_input=False,input_shape=(1,model.layers[-1].output_shape[-1])))

This allows me to compile the model, but then it fails on training due to a shape mismatch on matrices. It seems related to the difference between input shape and hidden_dim.
What would be the right way to insert an attentiondecoder into this kind of setup?

**Comment by jitoledo** [comment]
I think that "hidden_dim" is in fact the output dimension of the encoder and the input dimension of the decoder.  
Also It seems that by setting the "input_shape" property I am in fact, setting the output dimension of the decoder (which I think that in your example matches the input dimension of the encoder)

By creating the layer with AttentionDecoder(hidden_dim=model.layers[-1].output_shape[-1], output_length=16, state_input=False,input_shape=(1,model.layers[-1].output_shape[-1])))
I am able to train my model. I hope I'm using the layer correctly.

**Comment by farizrahman4u** [comment]
Attention decoder can be used independently without an encoder. And for the shape related error, update your Seq2seq and the error should go away.
