### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by mathewlee11** [farizrahman4u/seq2seq#39]
There's some small issues in bidirectional.py (nothing too bad, python 3's pickle library is pickle instead of cPickle and the division in some of the indexing doesn't work because it needs to be integers) that make it so the code doesn't run in python 3. I have this fixed on a local copy (should work for both 2 and 3), do you accept PRs?

**Comment by farizrahman4u** [comment]
Yes, we accept PRs (with pleasure).
