### ISSUE TITLE
Batch Size in Seq2Seq Model Causing Mismatch Dimension Error

### ISSUE THREAD

**Issue by LeavesBreathe** [farizrahman4u/seq2seq#4]
Hey Fariz, I've been really struggling with this error, and frankly, I'm not sure how to address it. 

You give a batch_size argument for your seq2seq model, and I'm wondering how this batch_size should relate to the batch_size parameter of `model.fit`

When I make `batch_size` of model.fit and seq2seq equivalent: I get the following error:

`IndexError: index 4 is out of bounds for axis 1 with size 4`

I have tried making the `batch_size` of seq2seq one less and one more than the model.fit `batch_size` and I'm met with this error:

`Input dimension mis-match. Input 1 (indices start at 0) has shape[0] == 3, but the output's size on that axis is 4.`

What exactly the difference between the `batch_size` of seq2seq and `batch_size` of model.fit()? Any help is greatly appreciated!

**Comment by farizrahman4u** [comment]
@LeavesBreathe batch_size in seq2seq is same as the batch_size in model.fit. **Make sure that the number of samples in your training data is divisible by batch_size.**

**Comment by LeavesBreathe** [comment]
Okay I will reevaluate and try that. I'll close this assuming it works.
