### ISSUE TITLE
pip install through ssh not working

### ISSUE THREAD

**Issue by jbingel** [farizrahman4u/seq2seq#42]
The installation instructions in the Readme (install with pip) did not work for me using ssh.

`sudo pip install git+ssh://github.com/farizrahman4u/seq2seq.git`

I don't know what problem pip had with ssh, but I just replaced `ssh` with `https` and it all went smoothly. This was on a Ubuntu 15.10 machine, but verified with 14.04 on a different machine. Maybe there should be a pointer to this in the Readme.

**Comment by farizrahman4u** [comment]
Maybe ssh is blocked by your network admin.

**Comment by jbingel** [comment]
Yeah, sure, it's probably something about my setup (although tested on two different systems, a server and a personal machine in a different network). But maybe someone else will have the same issue and won't directly have the idea to use https.
