### ISSUE TITLE
'Advanced' example (Seq2seq) not running

### ISSUE THREAD

**Issue by jbingel** [farizrahman4u/seq2seq#43]
The README example for the advanced seq2seq model (below) is not running. It returns a `TypeError: rnn() got an unexpected keyword argument 'mask'`. The `SimpleSeq2seq` examples work fine for me.

```
import seq2seq
from seq2seq.models import Seq2seq
model = Seq2seq(batch_input_shape=(16, 7, 5), hidden_dim=10, output_length=8, output_dim=20, depth=4)
model.compile(loss='mse', optimizer='rmsprop')
```

**Comment by farizrahman4u** [comment]
Update keras to its latest version.
