### ISSUE TITLE
lstms list in AttentionSeq2seq

### ISSUE THREAD

**Issue by senisioi** [farizrahman4u/seq2seq#46]
Could you explain the point of using the lstms list in the constructor of AttentionSeq2seq?

**Comment by farizrahman4u** [comment]
Stack of multiple lstm layers.

**Comment by senisioi** [comment]
Okay, but is it necessary to store the layers in a list? Isn't it enough to just call self.add()? I don't see where the list is being used explicitly, that's why I ask.
