### ISSUE TITLE
dimension mismatch error with attention model

### ISSUE THREAD

**Issue by qfzhu** [farizrahman4u/seq2seq#47]
Hi, I got an dimension mismatch error with attention model.

my model is:
`model.add(embeddings.Embedding(input_dim=len(chars)+1, output_dim=EMB_DIM, input_length=MAXLEN))
seq2seq = AttentionSeq2seq(input_dim=EMB_DIM, input_length=MAXLEN, hidden_dim=HIDDEN_SIZE, output_length=MAXLEN, output_dim=len(chars), depth=1)
model.add(seq2seq)
`
in the model:
`len(chars) = 1408, HIDDEN_SIZE=1000`

and got the error:
`ValueError: dimension mismatch in args to gemm (100,1000)x(1408,1000)->(100,1000)`
 
then I try to make the `HIDDEN_SIZE` equal to `len(chars)`, then model can run. is this a parameter error in attention model?

**Comment by farizrahman4u** [comment]
Are you running on the latest version of seq2seq?

**Comment by qfzhu** [comment]
yes

**Comment by qfzhu** [comment]
the error seems to happen when try `(batch_size*hidden_dim)*(output_dim*hidden_dim)`, may be the later needs a dimshuffle?
