### ISSUE TITLE
Handling of depth=1 in SimpleSeq2seq is inconsistent with output_dim

### ISSUE THREAD

**Issue by udibr** [farizrahman4u/seq2seq#55]
In all other cases (depth>1 or Seq2Seq) the usage of output_dim is to define an output generated from the LSTM hidden size using Dropout and TimeDistributedDense

However in the case of SimpleSeq2seq when depth happens to be 1 the output_dim is used to replace the hidden size on the ouput RNN.

I tripped over this because I feed a large number to ouput_dim (vocabulary size) and that required huge matrix to handle an RNN which such a huge hidden size which cause the code to hang (when using theano+gpu)
In any case this was not what I expected...

**Comment by farizrahman4u** [comment]
Fixed
