### ISSUE TITLE
AssertionError: Keyword argument not understood: batch_size

### ISSUE THREAD

**Issue by htw2012** [farizrahman4u/seq2seq#61]
Hello,I have met some error "AssertionError: Keyword argument not understood: batch_size",
Is it not right to pass the argument batch_size to Seq2seq?
code is 
`
import keras
from keras.models import Sequential
from keras.layers.embeddings import Embedding
from seq2seq.models import Seq2seq
from keras.preprocessing import sequence

vocab_size = 20000 #number of words
maxlen = 100 #length of input sequence and output sequence
embedding_dim = 200 #word embedding size
hidden_dim = 500 #memory size of seq2seq

embedding = Embedding(vocab_size, embedding_dim, input_length=maxlen)
seq2seq = Seq2seq(input_length=maxlen, input_dim=embedding_dim,hidden_dim=hidden_dim,
                  output_dim=embedding_dim, output_length=maxlen, batch_size=10, depth=4)

model = Sequential()
model.add(embedding)
model.add(seq2seq)`

**Comment by htw2012** [comment]
@farizrahman4u

**Comment by mbollmann** [comment]
`batch_size` is an argument for `model.fit()`, `model.predict()` etc., not for the constructor of a model.

**Comment by Jerrylu5683** [comment]
I have the same problem. I delete "batch_size=10" from parameters and it is still not right.
```Exception: If a RNN is stateful, a complete input_shape must be provided (including batch size).```
How did you resolve this problem?

**Comment by mbollmann** [comment]
By providing `input_shape` or `batch_input_shape` as described in the documentation:
http://keras.io/getting-started/sequential-model-guide/#specifying-the-input-shape
