### ISSUE TITLE
seq2seq layers in Keras 1.0 ?

### ISSUE THREAD

**Issue by amaiasalvador** [farizrahman4u/seq2seq#66]
Hello,

I was wondering if you are planning to adapt the seq2seq library to work with the latest Keras version. I am trying to get the AttentionDecoder to work in Keras 1.0, and I am getting errors due to the changes that were made in some of the layer's methods. I am currently trying to adapt it myself following [these guidelines](https://github.com/fchollet/keras/wiki/Porting-your-custom-layers-from-Keras-0.3-to-Keras-1.0), but I am no expert, so I wanted to ask you if you are planning to address this in the future.

Thanks !

**Comment by wboag** [comment]
+1

**Comment by linjun-pt** [comment]
+1

**Comment by chm90** [comment]
+1

**Comment by mrcx-pku** [comment]
+1

**Comment by farizrahman4u** [comment]
![Good news](https://www.google.co.in/imgres?imgurl=https%3A%2F%2Fcaptainawkwarddotcom.files.wordpress.com%2F2012%2F03%2Fgood-news1.jpg&imgrefurl=https%3A%2F%2Fcaptainawkward.com%2Ftag%2Fhappy-news%2F&docid=Lssjmf6SwaIzYM&tbnid=FLuUhiYe9YRSpM%3A&w=470&h=332&bih=667&biw=1366&ved=0ahUKEwiEn72k2M7NAhXMrI8KHUjEBjkQMwhEKBIwEg&iact=mrc&uact=8)

**Comment by farizrahman4u** [comment]
![good_news](https://cloud.githubusercontent.com/assets/11006006/16474841/b8ba55c4-3e97-11e6-9240-3c19c943ad82.jpg)

Seq2seq has been upgraded to Keras 1.0

**Comment by farizrahman4u** [comment]
![good_news](https://cloud.githubusercontent.com/assets/11006006/16475382/c6234c76-3e9b-11e6-8c80-fab86bb17e8c.jpg)


Seq2seq now supports Keras 1.0.

**Comment by chm90** [comment]
Who :D THANKYOU :+1:

**Comment by amaiasalvador** [comment]
Thank you !
