### ISSUE TITLE
Could you please update NTM, Stack RNN, Queue RNN to keras 1.0?

### ISSUE THREAD

**Issue by dytmas** [farizrahman4u/seq2seq#78]
I tried to update it myself according to https://github.com/fchollet/keras/wiki/Porting-your-custom-layers-from-Keras-0.3-to-Keras-1.0, but have some trouble. I always got some ValueError: dimension mismatch in args to gemm. Can you help? Thanks a lot!~

**Comment by farizrahman4u** [comment]
@dytmas 
Where is the original source code of Queue and Stack RNNs? Also try posting general requests on Keras's issues, it will reach more people. If you want to reach me personally, [join the Keras slack group](https://groups.google.com/forum/#!topic/keras-users/NnkGmDx3XmM).

@edersantana Can you look into NTM?

**Comment by dytmas** [comment]
sorry... I post it at a wrong place.
