### ISSUE TITLE
Two Dropouts behind each other

### ISSUE THREAD

**Issue by ftrier** [farizrahman4u/seq2seq#79]
Hello,
I am not sure if it is a bug. But in the for loop of the following line, there seems that two dropouts are stacked on top of each other. 
https://github.com/farizrahman4u/seq2seq/blob/123a2cfe9e5c4db41856eaff573b9d08cdb534dc/seq2seq/models.py#L150

**Comment by farizrahman4u** [comment]
Thanks. Fixed
