### ISSUE TITLE
any plan for attention seq2seq?

### ISSUE THREAD

**Issue by hugman** [farizrahman4u/seq2seq#8]
Thank you for great codes.

Do you have any plans to add 'attention' mechanism to your code as TensorFlow did. 

Check https://github.com/tensorflow/tensorflow/blob/master/tensorflow/models/rnn/seq2seq.py#L351

**Comment by farizrahman4u** [comment]
Yes. It is in progress. The bidirectional LSTM with hidden state propagation was made for this purpose.  Next we need an attention based  decoder. Should be ready in a few days.
