### ISSUE TITLE
Puzzle about the seq2seq algorithm

### ISSUE THREAD

**Issue by DvHuang** [farizrahman4u/seq2seq#81]
Thanks for your awesome contribution.
I'm still a bit doubtful about this frame,could you help me please.
From the paper 《Sequence to Sequence Learning with Neural Networks》,
for one sentence ,we encode every word in it. and use the last word's hidden state represent the sentence.
then we put it (the last word's hidden state) into the decode layer.
but in your code ,it seems put every word embedding into the decode layer.
please tell me ,either I misunderstanding your code or I misunderstanding the seq2seq frame.
thanks very much.

**Comment by DvHuang** [comment]
oh，I see! 
does the "return_sequences" param control what step into the decode layer?
when the param return_sequences=false ,there were only the last word's hidden state step into the next layer.
Thanks for your awesome contribution again.

**Comment by farizrahman4u** [comment]
Only the final context vector goes into the decoder input. The hidden state is also shared

**Comment by farizrahman4u** [comment]
.

**Comment by DvHuang** [comment]
Thanks very much ，thank you.
