### ISSUE TITLE
Error when trying out a simple example

### ISSUE THREAD

**Issue by shashankg7** [farizrahman4u/seq2seq#82]
HI,

I am trying out a simple application of seq2seq using your library. My application is learning to sort an integer sequence using seq2seq models. I am trying out the following code :

```python
import numpy as np
from keras.preprocessing.text import one_hot
import pdb


def encode(X,seq_len, vocab_size):
    x = np.zeros((len(X),seq_len, vocab_size), dtype=np.float32)
    for ind,batch in enumerate(X):
        for j, elem in enumerate(batch):
            x[ind, j, elem] = 1
    return x

def batch_gen(batch_size=32, seq_len=10, max_no=100):
    # Randomly generate a batch of integer sequences (X) and its sorted
    # counterpart (Y)
    x = np.zeros((batch_size, seq_len, max_no), dtype=np.float32)
    y = np.zeros((batch_size, seq_len, max_no), dtype=np.float32)

    while True:
        X = np.random.randint(max_no, size=(batch_size, seq_len))
        Y = np.sort(X, axis=1)

        for ind,batch in enumerate(X):
            for j, elem in enumerate(batch):
                x[ind, j, elem] = 1

        for ind,batch in enumerate(Y):
            for j, elem in enumerate(batch):
                y[ind, j, elem] = 1

        yield x, y
        x.fill(0.0)
        y.fill(0.0)
```
This is for data generation. For training I am using the following code:
```python
import seq2seq
from seq2seq.models import SimpleSeq2seq
from seq2seq.models import Seq2seq
import numpy as np
from data import batch_gen, encode
import pdb

# global params
batch_size=32
seq_len = 10
max_no = 100


#model = SimpleSeq2seq(input_dim=max_no, hidden_dim=10, output_length=seq_len,\
#                      output_dim=max_no)

model = Seq2seq(batch_input_shape=(batch_size, seq_len, max_no), hidden_dim=10,\
                output_length=seq_len, output_dim=max_no, depth=2)

model.compile(loss='categorical_crossentropy', optimizer='adam',
              metrics=['accuracy'])

for ind,(X,Y) in enumerate(batch_gen(batch_size, seq_len, max_no)):
    loss, acc = model.train_on_batch(X, Y)
    if ind % 250 == 0:
        testX = np.random.randint(max_no, size=(1, seq_len))
        test = encode(testX, seq_len, max_no)
        print testX
        #pdb.set_trace()
        y = model.predict(test, batch_size=1)
        print "actual sorted output is"
        print np.sort(testX)
        print "sorting done by RNN is"
        print np.argmax(y, axis=2)
        print "\n"
        # print loss, acc
```
I tried running with SimpleSeq2seq, but the results were not good, even for a relatively short sequence. Now I am trying to run Seq2seq. But when I run this I am getting following error: 

> 

Using Theano backend.
[[23 53 16 27  2  9 44 88 49  7]]
Traceback (most recent call last):
  File "model_seq2seq.py", line 30, in <module>
    y = model.predict(test, batch_size=1)
  File "/home/shashank/.local/lib/python2.7/site-packages/keras/models.py", line 464, in predict
    return self.model.predict(x, batch_size=batch_size, verbose=verbose)
  File "/home/shashank/.local/lib/python2.7/site-packages/keras/engine/training.py", line 1155, in predict
    batch_size=batch_size, verbose=verbose)
  File "/home/shashank/.local/lib/python2.7/site-packages/keras/engine/training.py", line 855, in _predict_loop
    batch_outs = f(ins_batch)
  File "/home/shashank/.local/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 531, in __call__
    return self.function(*inputs)
  File "/home/shashank/.local/lib/python2.7/site-packages/theano/compile/function_module.py", line 871, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/home/shashank/.local/lib/python2.7/site-packages/theano/gof/link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/home/shashank/.local/lib/python2.7/site-packages/theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
  File "/home/shashank/.local/lib/python2.7/site-packages/theano/scan_module/scan_op.py", line 951, in rval
    r = p(n, [x[0] for x in i], o)
  File "/home/shashank/.local/lib/python2.7/site-packages/theano/scan_module/scan_op.py", line 940, in <lambda>
    self, node)
  File "theano/scan_module/scan_perform.pyx", line 405, in theano.scan_module.scan_perform.perform (/home/shashank/.theano/compiledir_Linux-4.2--generic-x86_64-with-debian-jessie-sid-x86_64-2.7.12-64/scan_perform/mod.cpp:4316)
  File "/home/shashank/.local/lib/python2.7/site-packages/theano/gof/link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "theano/scan_module/scan_perform.pyx", line 397, in theano.scan_module.scan_perform.perform (/home/shashank/.theano/compiledir_Linux-4.2--generic-x86_64-with-debian-jessie-sid-x86_64-2.7.12-64/scan_perform/mod.cpp:4193)
ValueError: Shape mismatch: x has 32 rows but z has 1 rows
Apply node that caused the error: Gemm{no_inplace}(Subtensor{::, int64::}.0, TensorConstant{0.20000000298}, <TensorType(float32, matrix)>, lstmencoder_2_U_o_copy, TensorConstant{0.20000000298})
Toposort index: 5
Inputs types: [TensorType(float32, matrix), TensorType(float32, scalar), TensorType(float32, matrix), TensorType(float32, matrix), TensorType(float32, scalar)]
Inputs shapes: [(1, 10), (), (32, 10), (10, 10), ()]
Inputs strides: [(160, 4), (), (40, 4), (40, 4), ()]
Inputs values: ['not shown', array(0.20000000298023224, dtype=float32), 'not shown', 'not shown', array(0.20000000298023224, dtype=float32)]
Outputs clients: [[Elemwise{Composite{(clip((i0 + i1), i2, i3) * tanh(i4))}}(TensorConstant{(1, 1) of 0.5}, Gemm{no_inplace}.0, TensorConstant{(1, 1) of 0}, TensorConstant{(1, 1) of 1}, Elemwise{Composite{((clip((i0 + i1), i2, i3) * i4) + (clip((i5 + i6), i2, i3) * tanh(i7)))}}.0)]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
Apply node that caused the error: forall_inplace,cpu,scan_fn}(TensorConstant{10}, InplaceDimShuffle{1,0,2}.0, IncSubtensor{InplaceSet;:int64:}.0, IncSubtensor{InplaceSet;:int64:}.0, TensorConstant{10}, lstmencoder_2_U_o, lstmencoder_2_U_f, lstmencoder_2_U_i, lstmencoder_2_U_c)
Toposort index: 105
Inputs types: [TensorType(int64, scalar), TensorType(float32, 3D), TensorType(float32, (True, False, False)), TensorType(float32, (True, False, False)), TensorType(int64, scalar), TensorType(float32, matrix), TensorType(float32, matrix), TensorType(float32, matrix), TensorType(float32, matrix)]
Inputs shapes: [(), (10, 1, 40), (1, 32, 10), (1, 32, 10), (), (10, 10), (10, 10), (10, 10), (10, 10)]
Inputs strides: [(), (160, 160, 4), (1280, 40, 4), (1280, 40, 4), (), (40, 4), (40, 4), (40, 4), (40, 4)]
Inputs values: [array(10), 'not shown', 'not shown', 'not shown', array(10), 'not shown', 'not shown', 'not shown', 'not shown']
Outputs clients: [[], [], [InplaceDimShuffle{0,1,2}(forall_inplace,cpu,scan_fn}.2)]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

I think I am giving correct input dimensions. Can you please check what is wrong in this?

**Comment by farizrahman4u** [comment]
Will look into it, in the mean time there is a built-in Seq2seq layer for neural sorting, called `SoftShuffle`.

**Comment by farizrahman4u** [comment]
Ok, so the problem is that your Seq2seq model has batch_size of 32, but you are predicting for only 1 batch.  You could solve this by adding 31 empty (zero) batches to your input, and ignore them in the output.

**Comment by shashankg7** [comment]
Thanks for your reply. I will try to append some empty batches and check the results.
