### ISSUE TITLE
About the states 

### ISSUE THREAD

**Issue by DvHuang** [farizrahman4u/seq2seq#83]
I have a presumptuous request.
Please help me explain why the states's length is 5 and what in the state[2]. thank you.
![11](https://cloud.githubusercontent.com/assets/12111571/17088847/4d1d4072-5253-11e6-82ab-6b30ef71450a.png)
I know Closely linked with this is under code show in picture，but where is the "rnns" come from and  can‘t understand the code block.
I would be appreciated it if you could explain it just a little.thanks
![12](https://cloud.githubusercontent.com/assets/12111571/17088941/fd4f2262-5253-11e6-8de8-a007bddf22ed.png)

**Comment by farizrahman4u** [comment]
5 states : h_tm1, c_tm1, y_tm1, B_U, B_W
broadcast_state is for transferring hidden states from one LSTM layer to one or more LSTM layers.

**Comment by DvHuang** [comment]
Thanks for your enthusiastic answer。
Could you help me check out  whether my derivation is correct.
in the peek version:
y(t) = LSTM(s(t-1), y(t-1), C)
y(0) = LSTM(s0, C, C)

v = self.activation(K.dot(x, self.W_x) + self.b_x)   
y_tm1 += v
Does that mean we add the “V” to the “ytm1” , then operate it as an no peek version.
if aforementioned is right，
then the ”V“ should be equal "**y(t-1)" in the expression ：y(t) = LSTM ( s ( t-1 ) ,  y ( t-1 ) ,  C )
and the ytm1=states[2]=C,As I am right ?
Thank for your  any help.
