### ISSUE TITLE
Seq2seq: Encoder being added after Decoder

### ISSUE THREAD

**Issue by nabihach** [farizrahman4u/seq2seq#85]
In https://github.com/farizrahman4u/seq2seq/blob/master/seq2seq/models.py , line 147, encoder layers are being added after the first decoder layer. Is this a bug? Should these be decoders instead?

I tried replacing line 147 with:
`layer = LSTMDecoder2(hidden_dim=hidden_dim, output_length=output_length, state_input=broadcast_state, return_sequences=i<depth[0]-2, **kwargs)`

but it gives the error: 
`  File "/var/lib/try_seq2seq/seq2seq/seq2seq/layers/decoders.py", line 136, in assert_input_compatibility
    assert K.ndim(x) == 2, "LSTMDecoder requires 2D  input, not " + str(K.ndim(x)) + "D."
AssertionError: LSTMDecoder requires 2D  input, not 3D.
`

Any help would be appreciated.

**Comment by farizrahman4u** [comment]
Its not a bug.
