### ISSUE TITLE
using GPU

### ISSUE THREAD

**Issue by nabihach** [farizrahman4u/seq2seq#89]
I am planning to test your code using EC2's g2.2xlarge instance. It has an NVIDIA GPU with 1536 CUDA cores. What changes should I make to the nicolas_ivanov example code in order to get maximum benefit of the GPU? 
In particular, is it enough to just specify device=gpu in Theano flags?

Any help will be highly appreciated. Thanks

**Comment by shashankg7** [comment]
You dont need to make any changes. Using device='GPU' will suffice.
